version: "2.1"
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=netology
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  back:
    image: back
    environment:
      - MYSQL_HOST=mysql
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

  front:
    image: front
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy